service: loginCognito

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminGetUser
          Resource: !GetAtt UserPoolTest.Arn
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource: arn:aws:dynamodb:us-east-1:${aws:accountId}:table/Users
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:us-east-1:${aws:accountId}:table/Cart_v2
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource: arn:aws:dynamodb:us-east-1:${aws:accountId}:table/Cart_v2
        - Effect: Allow
          Action:
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:us-east-1:${aws:accountId}:table/Cart_v2
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource: arn:aws:dynamodb:us-east-1:${aws:accountId}:table/Cart_v2/index/UserIdIndex

  environment:
    COGNITO_CLIENT_ID: !Ref testClientIaca
    COGNITO_POOL_ID: !Ref UserPoolTest
  httpApi:
    authorizers:
      CognitoAuthorizerTest:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPoolTest.ProviderURL
        audience:
          - !Ref testClientIaca

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - "@aws-sdk/*"
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

resources:
  Resources:
    UserPoolTest:
      Type: AWS::Cognito::UserPool
      Properties:
        DeletionProtection: ACTIVE
        UserPoolName: UserPoolTest
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 7
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
    testClientIaca:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: testClientIaca
        UserPoolId: !Ref UserPoolTest
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 3
        RefreshTokenValidity: 1440 #60 days

    CartTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Cart_v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: CartId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: CartId
            KeyType: HASH
          - AttributeName: UserId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: UserId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: UserId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

functions:
  signUp:
    handler: src/functions/signUp.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-up
  accountConfirmation:
    handler: src/functions/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/account-confirmation
  signIn:
    handler: src/functions/signIn.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-in
  refreshToken:
    handler: src/functions/refreshToken.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh-token
  forgotPassword:
    handler: src/functions/forgotPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/forgot-password
  resetPassword:
    handler: src/functions/resetPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/reset-password
  profile:
    handler: src/functions/profile.handler
    events:
      - httpApi:
          method: GET
          path: /profile
          authorizer:
            name: CognitoAuthorizerTest
  getCart:
    handler: src/functions/getCart.handler
    events:
      - httpApi:
          method: GET
          path: /cart
          authorizer:
            name: CognitoAuthorizerTest
  addToCart:
    handler: src/functions/addToCart.handler
    events:
      - httpApi:
          method: POST
          path: /cart
          authorizer:
            name: CognitoAuthorizerTest
  updateCartItem:
    handler: src/functions/updateCartItem.handler
    events:
      - httpApi:
          method: PUT
          path: /cart/{cartId}
          authorizer:
            name: CognitoAuthorizerTest
  deleteCartItem:
    handler: src/functions/deleteCartItem.handler
    events:
      - httpApi:
          method: DELETE
          path: /cart/{cartId}
          authorizer:
            name: CognitoAuthorizerTest
